### ISSUE TITLE
"Ding" before announcement starts

### ISSUE THREAD

**Issue by jmchatton** [umts/realtime-announcements#4]
To capture passengers' attention before important information is dictated. Only one ding would be necessary at the beginning of a sequence of departures if they are triggered at the same time. [Here's an example.](https://youtu.be/JR-0ZyE70B4?t=27s)

**Comment by dfaulken** [comment]
To make this happen, we'd need a `.wav` file in `voice/fragments` , e.g. `voice/fragments/ding.wav`, and to add the following line:

```ruby
play fragment: 'ding'
```

in between these two lines:

https://github.com/umts/realtime-announcements/blob/62afd7d40df5e1b4bfd2fc29b799551b26dd4d8c/announcer.rb#L157-L158

**Comment by jmchatton** [comment]
For what it's worth, I was looking for open source ding sounds and [this one](http://soundbible.com/1598-electronic-chime.html) sounds nice.

**Comment by dfaulken** [comment]
@jmchatton I added the ding sound you had suggested. I like it as well. About a second of silence follows the ding before the first announcement starts, which seems appropriate.
