### ISSUE TITLE
R16 should be announced as 10S

### ISSUE THREAD

**Issue by jmchatton** [umts/realtime-announcements#5]
Westfield Pavilion announced the `R16`, which is an internal route number for the `10S` (no one in the public knows what `R16` is). This should be announced as `10S`.

**Comment by dfaulken** [comment]
To make this change, we would just need to replace the file `voice/routes/10016.wav` with a recording where "10S" is spoken.

**Comment by jmchatton** [comment]
In the [shared Box folder](https://umass.box.com/s/jtx2xbcr1hdynb61pw1sjnayh0kofpvk), there are recordings for both 10S headsigns. If you just want the route number, you could probably rip it from those.

**Comment by dfaulken** [comment]
I've made the change. Because there hasn't been movement on #2 from PVTA, we will still need to update the already deployed installations... somehow.

**Comment by jmchatton** [comment]
Let me see what I can do.

**Comment by jmchatton** [comment]
For what it's worth, other routes where the `ShortName` and `RouteAbbreviation` differ should be considered in future deployments. SATCo is the only property that has these, I believe. Here's a list of them:

`B9` (`OWL`)
`920` (`P20E`)
`921` (`P21E`)

**Comment by dfaulken** [comment]
This project doesn't directly use either the `ShortName` or the `RouteAbbreviation`. It announces routes according to their ID in Avail.

Here are what the announcements say for those three routes (at time of writing):

Avail ID | Announcement says...
--- | ---
10009 | No such announcement
10920 | "P20 Express"
10921| "P21 Express"

**Comment by jmchatton** [comment]
I see. So the P20E and P21E look good. The OWL stays on the Westfield State campus so I don't think we need to worry about that.

**Comment by dfaulken** [comment]
Once the installation at Olver Transit Pavilion is running the changes from #2, we can close this. It will pull down the new announcement automagically.

**Comment by jmchatton** [comment]
How could one know if Olver was running these changes? Jim said he updated the machine there, but it still is playing a computer-generated recording.

**Comment by werebus** [comment]
It sounds like you answered your own question?

**If** the deployed code has been updated past that point, then it should auto-update at 4:00am, and the current state of the software is that it has an announcement for the "10s". Has a full day elapsed since the update?

**Comment by werebus** [comment]
Or, of course, there's some other unknown problem which Jim will have to trouble-shoot.

**Comment by jmchatton** [comment]
Yes, Jim went over there on Thursday, but I heard the computer-generated recording yesterday.

**Comment by dfaulken** [comment]
Hi @jmchatton, when Olver announcements are up and running again you or I should remember to head over and make sure this recording is working properly.

**Comment by werebus** [comment]
Jim says that this _particular_ site died.
